baseURL: https://ldw.solutions/
theme: LoveIt
title: LDW Solutions | Blog
languageCode: en
languageName: English
hasCJKLanguage: false
paginate: 12
enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true
ignoreErrors:
  - error-remote-getjson
  - error-missing-instagram-accesstoken
author:
  name: LDW Solutions
  email: "contatos@ldw.solutions"
  link: "https://ldw.solutions/contatos.html"
menu:
  main:
    - weight: 1
      identifier: posts
      name: Posts
      url: /posts/
    - weight: 2
      identifier: tags
      name: Tags
      url: /tags/
    - weight: 3
      identifier: categories
      name: Categories
      url: /categories/
    - weight: 4
      identifier: ldw
      name: LDW Solutions
      url: https://ldw.solutions
params:
  defaultTheme: dark
  gitRepo: "https://github.com/lekodeveloperweb/blog.ldw.solutions"
  fingerprint: ""
  dateFormat: 2006-01-02
  title: "LDW Solutions | Blog"
  description: "Thoughts, ideas, turorials, techonologies, life of developer."
  images:
    - https://ldw.solutions/assets/images/marca-tipo-rgb.png
  header:
    desktopMode: fixed
    mobileMode: auto
    title:
      logo: "https://ldw.solutions/assets/images/marca-tipo-rgb.png"
      name: ""
      pre: ""
      post: ""
      typeit: false
  footer:
    enable: true
    hugo: true
    copyright: true
    author: true
    since: 2015
  section:
    paginate: 20
    dateFormat: 01-02
    rss: 10
  list:
    paginate: 20
    dateFormat: 01-02
    rss: 10
  app:
    title: LDW Solutions | Blog
    noFavicon: false
    svgFavicon: "https://ldw.solutions/assets/images/icons/favicon.ico"
    themeColor: "#ffffff"
    iconColor: "#5bbad5"
    tileColor: "#dcb34c"
  search:
    enable: true
    type: lunr
    contentLength: 4000
    placeholder: ""
    maxResultLength: 10
    snippetLength: 30
    highlightTag: em
    absoluteURL: false
  home:
    rss: 10
    profile:
      enable: true
      avatarURL: /images/personal-profile.jpg
      title: "Alex Leko"
      subtitle: "Leko Developer Web Solutions"
      typeit: true
      social: true
      disclaimer: "Thoughts, ideas, turorials, techonologies, life of developer."
    posts:
      enable: true
      paginate: 6
      defaultHiddenFromHomePage: false
  social:
    GitHub: https://github.com/lekodeveloperweb
    Linkedin: "https://www.linkedin.com/in/lekodeveloperweb/"
    Twitter: "https://twitter.com/LekoDeveloper"
    Instagram: "https://www.instagram.com/_alexleko_/"
    Facebook: "https://www.facebook.com/alexlekooficial"
    Email: contatos@ldw.solutions
    RSS: true
  page:
    share:
      enable: true
      Twitter: true
      Facebook: true
      Linkedin: true
      Whatsapp: true
      Pinterest: false
      Tumblr: false
      HackerNews: true
      Reddit: true
      VK: false
      Buffer: false
      Xing: false
      Line: false
      Instapaper: false
      Pocket: true
      Flipboard: false
      Weibo: true
      Blogger: false
      Baidu: false
      Odnoklassniki: false
      Evernote: false
      Skype: false
      Trello: false
      Mix: false
    comment:
      enable: true
      disqus:
        enable: true
        shortname: "ldwsolucoesinteligentes"
  cookieconsent:
    enable: true
    content:
      message: ""
      dismiss: ""
      link: "https://ldw.solutions/privacy-policy/"
  compatibility:
    polyfill: false
    objectFit: false
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
Permalinks:
  posts: :filename
mediaTypes:
  text/plain:
    suffixes:
      - md
outputFormats:
  MarkDown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML