version: '3'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: ldw.solutions/blog:latest
    container_name: ldw-blog
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.ldw.solutions`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls.certresolver=ldwresolver"
    networks:
      - default

networks:
  default:
    external: true
    name: ldwsolutions
